services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\CmsLikeBundle\Controller\:
    resource: '../../Controller/'
  Tourze\CmsLikeBundle\Repository\:
    resource: '../../Repository/'
  Tourze\CmsLikeBundle\Service\:
    resource: '../../Service/'
    public: true
  Tourze\CmsLikeBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true
  Tourze\CmsLikeBundle\Procedure\:
    resource: '../../Procedure/'
